package net.sldt_team.gameEngine.sound;

public enum EnumSoundLoadError {
    ERROR_NULL,
    ERROR_IO,
    ERROR_UNKNOWN_FORMAT,
    ERROR_INVALID_NAME,
    ERROR_INVALID_ENUM,
    ERROR_INVALID_VALUE,
    ERROR_INVALID_OPERATION,
    ERROR_FILE_FINDER,
    ERROR_DECODER_FAILURE,
    ERROR_MEMORY_OUT,
    ERROR_INVALID_CHANEL_FORMAT
}
